(specifications->manifest
  (list "clang-toolchain@14.0.6"
        "python-sphinx"
        "graphviz"
        "doxygen"
        "uncrustify"
        "git"
        "grep"
        "sed"
        "valgrind"
        "python-yapf"
        "cmakelang"
        "cppcheck"
        "make"
        "astyle"
        "lesspipe"
        "vim"
        "binutils"
        "coreutils"
        "plocate"
        "cmake@3.25"
        "hipamd"
        "rocprim"
        "gdb"
	"kokkos-hip"
        "gcc-toolchain@11"))

